apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-pi
spec:
  driver:
    coreLimit: 1200m
    cores: 1
    labels:
      version: 2.3.0
    memory: 512m
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.3.0
    memory: 512m
  image: "gcr.io/spark-operator/spark-py:v3.1.1"
  deps:
    pyFiles:
      - local:///opt/spark/examples/src/main/python/py_container_checks.py
      - gs://spark-data/python-dep.zip
